### ISSUE TITLE
Building type-safe wrappers around mpd.Attrs

### ISSUE THREAD

**Issue by mdlayher** [fhs/gompd#31]
Hello!  Been playing with this package recently and it seems to work rather well.  The API is nice too, but my one complaint is that since everything is a `map[string]string`, it requires manual parsing to deal with types such as integers, or compound fields such as `audio` (ex: `44100:16:2`).

To remedy this issue, I've been working on: https://github.com/mdlayher/mpdx.

As stated, package `mpdx` is an extension of package `mpd`.  I built it to nicely wrap some of the functions provided by this package.  It returns `struct` types with standard field names and types.

Is this functionality something you'd be interested in merging into your package?  If not, I'm happy to maintain `mpdx` as an extension to this package.  Let me know!

**Comment by fhs** [comment]
Nice work.

Yes, I've known this problem of manually parsing field for a long time, and I even thought of creating something like mpdx myself. My original decision to leave everything as map[string]string was due to mpd spec not documenting all the fields.

That said, I think it's better not to merge mpdx into this package. I like small packages that do one thing rather than one monolithic package that do everything. Good luck with mpdx!

**Comment by mdlayher** [comment]
Makes sense to me.  Thanks for your input!
